# Generated by Django 4.2.17 on 2025-01-15 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
    ]
