# Generated by Django 4.2.17 on 2025-01-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(default=2),
        ),
    ]
